### ISSUE TITLE
Compute cell from coordinate

### ISSUE THREAD

**Issue by dbkaplun** [rileyjshaw/terra#25]
Would be great if I could easily determine which cell is under the mouse cursor on click.

**Comment by rileyjshaw** [comment]
Hmm... good point! Since handling cross-browser canvas-relative coordinates can get verbose, I'm hesitant to throw it directly into the library. Once you have the x and y coords within the canvas it should be fairly straightforward:

``` javascript
function getCellFromCoords (x, y) {
  return {
    x: Math.floor(x / cellSize),
    y: Math.floor(y / cellSize)
  }
}
```

[cellSize](http://rileyjshaw.com/terra/#cellSize) defaults to 10. Let me know what you think!

**Comment by rileyjshaw** [comment]
If you're looking for a good way to translate a click event into canvas coordinates, I've found [this method](https://github.com/rileyjshaw/tic-attack-toe/blob/8669e19767852ba1896c069f68c546bb6b22b56f/scripts/main.js#L41-L61) works pretty well :)

**Comment by rileyjshaw** [comment]
@dbkaplun looking back on this, I still feel like click-handling should be handled outside of the core library. Cool if I close this?

**Comment by rileyjshaw** [comment]
(And if you ended up making a working demo with click-handling I'd love to see it!)
